#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 10 19:52:16 2019

@author: li
"""
import numpy as np 
import matplotlib.pyplot as plt


x0  =  0
y0  =  1
xf  =  1







def euler(step,lamb):
    n=int((xf-x0)/step)
    x  = np.linspace(x0 , xf , n+1)
    y  =  np.zeros(n+1)
    y[0] = y0
    err = y



    for i in range(1,n):
        y[i]= step*(-lamb*x[i-1])+y[i-1]
        err[i]=-lamb*(step*i)-y[i]

    plt.plot(x, err)
    plt.yscale('log')
    plt.show()

lam=[0.001,0.01,0.1,1,10,100,1000]
stepe=[0.001,0.01,0.1]
for i in range(len(lam)):
    for j in range(len(stepe)):
        euler(stepe[j],lam[i])
